language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

cache: cargo

matrix:
  fast_finish: true

script:
  - cargo build --verbose --examples
  - cargo test --verbose

notifications:
  email: false